<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-07 11:59

import django.db.models.deletion
import pgvector.django.vector
=======
# Generated by Django 5.2.7 on 2025-10-08 14:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> 3dd8b20559b1cf4fb28fc32a7b00c1f326172efe
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("metadata", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_summary", models.TextField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmgm.chatroom"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("sent_time", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(null=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                (
                    "related_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nmgm.message",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmgm.chatroom"
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nmgm.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmgm.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatroomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmgm.chatroom"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmgm.user"
                    ),
                ),
=======
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='관계 키워드 이름', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='채팅방 이름 또는 상대방 이름', max_length=200)),
                ('platform', models.CharField(choices=[('KAKAO', '카카오톡'), ('INSTA', '인스타그램'), ('SLACK', '슬랙')], default='KAKAO', help_text='채팅 플랫폼 종류', max_length=10)),
                ('profile_image', models.ImageField(blank=True, help_text='채팅방 대표 프로필 이미지', null=True, upload_to='profile_pics/')),
                ('last_message_preview', models.CharField(blank=True, help_text='마지막 대화 미리보기', max_length=255)),
                ('last_message_time', models.DateTimeField(blank=True, help_text='마지막 대화 시간', null=True)),
                ('summary_text', models.TextField(blank=True, help_text='AI가 요약한 대화 문장')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, related_name='chat_rooms', to='nmgm.keyword')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHabitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, help_text='AI의 주간 종합 피드백')),
                ('positive_score', models.IntegerField(default=0, help_text='긍정 감정 점수 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_report', to=settings.AUTH_USER_MODEL)),
>>>>>>> 3dd8b20559b1cf4fb28fc32a7b00c1f326172efe
            ],
        ),
    ]
