# Generated by Django 5.2.7 on 2025-10-10 06:33

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmgm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="topic_summary",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
