# Generated by Django 5.2.7 on 2025-10-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmgm", "0002_thread_metadata_alter_chatroom_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
